import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import InstallPrompt from "@/components/InstallPrompt";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tiny Lessons",
  description: "Learn anything fast with visual, just-in-time chapters.",
  manifest: "/manifest.json", // This will be auto-generated by the route, but good to link explicitly? No, Next App Router handles manifest via convention if manifest.ts exists. 
  // Wait, I created app/manifest.ts. Next will serve it at /manifest.webmanifest or /manifest.json. 
  // Next docs say: "The manifest file is served at /manifest.webmanifest".
  // But browser looks for link rel="manifest".
  // Next.js automatically adds the link tag if manifest.ts exists!
  // So I don't need to add it here.
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "TinyLessons",
  },
  formatDetection: {
    telephone: false,
  },
};

export const viewport = {
  themeColor: "#f59e0b",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-gray-50 text-gray-900 min-h-screen flex flex-col`}
      >
        <main className="flex-grow">
          {children}
        </main>

        <footer className="py-12 text-center text-sm text-gray-500 border-t border-gray-200 bg-white">
          <div className="max-w-7xl mx-auto px-6">
            <div className="flex flex-wrap justify-center gap-x-8 gap-y-4 mb-4">
              <a href="/privacy" className="hover:text-gray-900 transition-colors">Privacy Policy</a>
              <a href="/terms" className="hover:text-gray-900 transition-colors">Terms of Service</a>
              <a href="/contact" className="hover:text-gray-900 transition-colors">Contact Us</a>
            </div>
            <p>© {new Date().getFullYear()} Tiny Lessons. All rights reserved.</p>
          </div>
        </footer>
        <InstallPrompt />
      </body>
    </html>
  );
}
