import Link from 'next/link'
import { ChevronLeft } from 'lucide-react'

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            <div className="max-w-3xl mx-auto px-6 py-12">
                <Link href="/" className="inline-flex items-center text-sm text-gray-500 hover:text-gray-900 mb-8 transition-colors">
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Back to Home
                </Link>

                <h1 className="text-3xl font-bold text-gray-900 mb-8">Terms of Service</h1>

                <div className="prose prose-gray max-w-none">
                    <p>Last updated: {new Date().toLocaleDateString()}</p>

                    <h2>1. Acceptance of Terms</h2>
                    <p>By accessing or using our services, you agree to be bound by these Terms of Service.</p>

                    <h2>2. Use of Service</h2>
                    <p>You agree to use the service only for lawful purposes and in accordance with these Terms.</p>

                    <h2>3. Intellectual Property</h2>
                    <p>The content generated by our platform is for your personal use. The underlying technology and design remain our property.</p>

                    <h2>4. AI Generated Content</h2>
                    <p>Our service uses Artificial Intelligence to generate content. While we strive for accuracy, AI can make mistakes. Please verify important information independently.</p>

                    <h2>5. Limitation of Liability</h2>
                    <p>To the fullest extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages.</p>
                </div>
            </div>
        </div>
    )
}
